name: ESLint CI

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12
    
      - name: Install modules
        run: npm ci
        
      - name: Run linter
        run: npm run lint

